version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: sgbr-teste
        container_name: sgbr-teste
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        networks:
            - sgbr-teste-network

    db:
        image: mysql:8.0
        container_name: sgbr-teste-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: sgbr-teste
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - sgbr-teste-network

networks:
    sgbr-teste-network:
        driver: bridge
